### ISSUE TITLE
it doesnt work i get in to game but it dont work

### ISSUE THREAD

**Issue by 9in6is69** [ZeWhiteHatHacker/krunker.io-hacks-2019#3]

**Comment by ZeWhiteHatHacker** [comment]
**Hey dude I have officially abandoned this project but have a new one rolling! Tutorial on how to get the hack out soon on my YTB channel: https://cutit.org/GoBayMax**

Some features are:
_- AimBot, Aim Assiter, Trigger Bot
- Auto BHop + Auto Slide BHop
- Auto Reload
- Spin Bot
- No Death Delay
- No Recoil
- Aim Delta: Slow, Medium, Fast, MethHead
- Burst Shot
- Force Scope
- Super Gun_

Soon features:
- No BAD WORD filter for chat etc
- Aimbot accuracy math stuff
- Maybe more il see
